### ISSUE TITLE
extract files failed

### ISSUE THREAD

**Issue by zhuang137** [LineageOS/android_device_xiaomi_ginkgo#1]
these files are not found!  Should I remove these files when extract?  
Thanks!

      !! vendor/firmware/fpctzappfingerprint.b00: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b01: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b02: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b03: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b04: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b05: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b06: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b07: file not found in source
    !! vendor/firmware/fpctzappfingerprint.mdt: file not found in source
    !! vendor/firmware/goodixfp.b00: file not found in source
    !! vendor/firmware/goodixfp.b01: file not found in source
    !! vendor/firmware/goodixfp.b02: file not found in source
    !! vendor/firmware/goodixfp.b03: file not found in source
    !! vendor/firmware/goodixfp.b04: file not found in source
    !! vendor/firmware/goodixfp.b05: file not found in source
    !! vendor/firmware/goodixfp.b06: file not found in source
    !! vendor/firmware/goodixfp.b07: file not found in source
    !! vendor/firmware/goodixfp.mdt: file not found in source
    !! vendor/etc/sensors/sns_reg_config: file not found in source
    !! vendor/lib/libmmcamera_atmel_at24c32e_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_irs1645.so: file not found in source
    !! vendor/lib/libmmcamera_le2464c_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_le2464c_master_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_onsemi_cat24c16_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_onsemi_cat24c32_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_onsemi_cat24c32_imx362_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_rohm_brcg064gwz_3_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_s5k3m2xm.so: file not found in source
    !! vendor/lib/libmmcamera_s5k3m2xx.so: file not found in source
    !! vendor/lib/libmmcamera_sony_imx298_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_sony_imx378_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_sunny_gt24c64a_imx376_eeprom.so: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b00: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b01: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b02: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b03: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b04: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b05: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b06: file not found in source
    !! vendor/firmware/fpctzappfingerprint.b07: file not found in source
    !! vendor/firmware/fpctzappfingerprint.mdt: file not found in source
    !! vendor/firmware/goodixfp.b00: file not found in source
    !! vendor/firmware/goodixfp.b01: file not found in source
    !! vendor/firmware/goodixfp.b02: file not found in source
    !! vendor/firmware/goodixfp.b03: file not found in source
    !! vendor/firmware/goodixfp.b04: file not found in source
    !! vendor/firmware/goodixfp.b05: file not found in source
    !! vendor/firmware/goodixfp.b06: file not found in source
    !! vendor/firmware/goodixfp.b07: file not found in source
    !! vendor/firmware/goodixfp.mdt: file not found in source
    !! vendor/etc/sensors/sns_reg_config: file not found in source
    !! vendor/lib/libmmcamera_atmel_at24c32e_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_irs1645.so: file not found in source
    !! vendor/lib/libmmcamera_le2464c_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_le2464c_master_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_onsemi_cat24c16_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_onsemi_cat24c32_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_onsemi_cat24c32_imx362_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_rohm_brcg064gwz_3_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_s5k3m2xm.so: file not found in source
    !! vendor/lib/libmmcamera_s5k3m2xx.so: file not found in source
    !! vendor/lib/libmmcamera_sony_imx298_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_sony_imx378_eeprom.so: file not found in source
    !! vendor/lib/libmmcamera_sunny_gt24c64a_imx376_eeprom.so: file not found in source

**Comment by gabrc52** [comment]
What are you trying to do? I'm not too knowledgeable in this, but some are .so files which are compiled library, which probably are closed source binary blobs for the camera, fingerprint, etc

**Comment by zhuang137** [comment]
> What are you trying to do? I'm not too knowledgeable in this, but some are .so files which are compiled library, which probably are closed source binary blobs for the camera, fingerprint, etc

Thanks!I have solved the problem!I wll close it
